// Code generated by tools/dataset; DO NOT EDIT.
package sprite

import "github.com/mayanklad/pokecrt/internal/catalog"

const DatasetID = "3d5af3be715de18bf313b0b00c87c14fabcee8c510d96f0a6fa4ac526303e47e"

var generatedAssets = []Asset{
	{Key: catalog.VariantKey{SpeciesID: 1, FormID: "standard", Gender: "default", Palette: "regular"}, Path: "assets/0001-standard-default-regular.png", SHA256: "d53887ac605e4f9ff8a282657a05daafb361258d866612f8c1686cc8065cd8e7", SourceSHA256: "a3bd4708f11413968541a177e5d05363f913b3e961a69f96fc342a419d28aca2", SourceURL: "https://raw.githubusercontent.com/darknesspwnsu/pokesprite-v2/32ab52ea6b61871da34d9a3c61c7760c65a37af7/pokemon/regular/bulbasaur.png", SourceProvider: "msikma/pokesprite", Width: 20, Height: 19},
	{Key: catalog.VariantKey{SpeciesID: 6, FormID: "standard", Gender: "default", Palette: "regular"}, Path: "assets/0006-standard-default-regular.png", SHA256: "fc7adb4bf5b2b436598c920765cc8c4732ed74c15697b9ed9a3bd79f83e2a28f", SourceSHA256: "8f240d20cf6ea209e82870cb052c244fcc51136d0d1278021253770654285af4", SourceURL: "https://raw.githubusercontent.com/darknesspwnsu/pokesprite-v2/32ab52ea6b61871da34d9a3c61c7760c65a37af7/pokemon/regular/charizard.png", SourceProvider: "msikma/pokesprite", Width: 44, Height: 39},
	{Key: catalog.VariantKey{SpeciesID: 7, FormID: "standard", Gender: "default", Palette: "regular"}, Path: "assets/0007-standard-default-regular.png", SHA256: "acd07b04795108ca89e82937798f95a1001fb079de8c36915784a76436a29866", SourceSHA256: "b86d6f10fcdef1a54d02647e92d8a28db221f7087076a89c0200b3bffe4100ea", SourceURL: "https://raw.githubusercontent.com/darknesspwnsu/pokesprite-v2/32ab52ea6b61871da34d9a3c61c7760c65a37af7/pokemon/regular/squirtle.png", SourceProvider: "msikma/pokesprite", Width: 21, Height: 17},
}
