// Code generated by tools/dataset; DO NOT EDIT.
package catalog

const DatasetID = "3d5af3be715de18bf313b0b00c87c14fabcee8c510d96f0a6fa4ac526303e47e"

var generatedSpecies = []Species{
	{ID: 1, Name: "Bulbasaur", Slug: "bulbasaur", Aliases: []string{"bulbasaur"}, Generation: 1, Color: "green", Stage: 1, Baby: false, Legendary: false, Mythical: false, EvolvesFrom: 0, EvolvesTo: []int{2}, Forms: []Form{{ID: "standard", Name: "Standard", Types: []string{"grass", "poison"}, DefaultGender: "default", Genders: []string{"default"}, SourceAliases: []string(nil)}}},
	{ID: 2, Name: "Ivysaur", Slug: "ivysaur", Aliases: []string{"ivysaur"}, Generation: 1, Color: "green", Stage: 2, Baby: false, Legendary: false, Mythical: false, EvolvesFrom: 1, EvolvesTo: []int{3}, Forms: []Form{{ID: "standard", Name: "Standard", Types: []string{"grass", "poison"}, DefaultGender: "default", Genders: []string{"default"}, SourceAliases: []string(nil)}}},
	{ID: 3, Name: "Venusaur", Slug: "venusaur", Aliases: []string{"venusaur"}, Generation: 1, Color: "green", Stage: 3, Baby: false, Legendary: false, Mythical: false, EvolvesFrom: 2, EvolvesTo: []int(nil), Forms: []Form{{ID: "standard", Name: "Standard", Types: []string{"grass", "poison"}, DefaultGender: "default", Genders: []string{"default"}, SourceAliases: []string(nil)}, {ID: "gmax", Name: "Gigantamax", Types: []string{"grass", "poison"}, DefaultGender: "default", Genders: []string{"default"}, SourceAliases: []string(nil)}, {ID: "mega", Name: "Mega", Types: []string{"grass", "poison"}, DefaultGender: "default", Genders: []string{"default"}, SourceAliases: []string(nil)}}},
	{ID: 4, Name: "Charmander", Slug: "charmander", Aliases: []string{"charmander"}, Generation: 1, Color: "red", Stage: 1, Baby: false, Legendary: false, Mythical: false, EvolvesFrom: 0, EvolvesTo: []int{5}, Forms: []Form{{ID: "standard", Name: "Standard", Types: []string{"fire"}, DefaultGender: "default", Genders: []string{"default"}, SourceAliases: []string(nil)}}},
	{ID: 5, Name: "Charmeleon", Slug: "charmeleon", Aliases: []string{"charmeleon"}, Generation: 1, Color: "red", Stage: 2, Baby: false, Legendary: false, Mythical: false, EvolvesFrom: 4, EvolvesTo: []int{6}, Forms: []Form{{ID: "standard", Name: "Standard", Types: []string{"fire"}, DefaultGender: "default", Genders: []string{"default"}, SourceAliases: []string(nil)}}},
	{ID: 6, Name: "Charizard", Slug: "charizard", Aliases: []string{"charizard"}, Generation: 1, Color: "red", Stage: 3, Baby: false, Legendary: false, Mythical: false, EvolvesFrom: 5, EvolvesTo: []int(nil), Forms: []Form{{ID: "standard", Name: "Standard", Types: []string{"fire", "flying"}, DefaultGender: "default", Genders: []string{"default"}, SourceAliases: []string(nil)}, {ID: "gmax", Name: "Gigantamax", Types: []string{"fire", "flying"}, DefaultGender: "default", Genders: []string{"default"}, SourceAliases: []string(nil)}, {ID: "mega-x", Name: "Mega X", Types: []string{"fire", "dragon"}, DefaultGender: "default", Genders: []string{"default"}, SourceAliases: []string(nil)}, {ID: "mega-y", Name: "Mega Y", Types: []string{"fire", "flying"}, DefaultGender: "default", Genders: []string{"default"}, SourceAliases: []string(nil)}}},
	{ID: 7, Name: "Squirtle", Slug: "squirtle", Aliases: []string{"squirtle"}, Generation: 1, Color: "blue", Stage: 1, Baby: false, Legendary: false, Mythical: false, EvolvesFrom: 0, EvolvesTo: []int{8}, Forms: []Form{{ID: "standard", Name: "Standard", Types: []string{"water"}, DefaultGender: "default", Genders: []string{"default"}, SourceAliases: []string(nil)}}},
	{ID: 8, Name: "Wartortle", Slug: "wartortle", Aliases: []string{"wartortle"}, Generation: 1, Color: "blue", Stage: 2, Baby: false, Legendary: false, Mythical: false, EvolvesFrom: 7, EvolvesTo: []int{9}, Forms: []Form{{ID: "standard", Name: "Standard", Types: []string{"water"}, DefaultGender: "default", Genders: []string{"default"}, SourceAliases: []string(nil)}}},
	{ID: 9, Name: "Blastoise", Slug: "blastoise", Aliases: []string{"blastoise"}, Generation: 1, Color: "blue", Stage: 3, Baby: false, Legendary: false, Mythical: false, EvolvesFrom: 8, EvolvesTo: []int(nil), Forms: []Form{{ID: "standard", Name: "Standard", Types: []string{"water"}, DefaultGender: "default", Genders: []string{"default"}, SourceAliases: []string(nil)}, {ID: "gmax", Name: "Gigantamax", Types: []string{"water"}, DefaultGender: "default", Genders: []string{"default"}, SourceAliases: []string(nil)}, {ID: "mega", Name: "Mega", Types: []string{"water"}, DefaultGender: "default", Genders: []string{"default"}, SourceAliases: []string(nil)}}},
}

var generatedAliases = map[string]int{
	"bulbasaur":  0,
	"ivysaur":    1,
	"venusaur":   2,
	"charmander": 3,
	"charmeleon": 4,
	"charizard":  5,
	"squirtle":   6,
	"wartortle":  7,
	"blastoise":  8,
}
